name: Ddeploy image to ghcr
on:
  workflow_dispatch: #github页面手动触发
  push:
    branches:
      - main

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Image'
        run: |
          docker build . --tag ghcr.io/small2space/cloudflare-warp:latest
          docker push ghcr.io/small2space/cloudflare-warp:latest
